# -*- coding: utf-8 -*-
"""Generate loadtest seed SQL + mobiles.csv for JMeter."""
from __future__ import annotations

from datetime import date, timedelta
from pathlib import Path
import time

ROOT = Path(__file__).resolve().parents[2]
SQL_OUT = ROOT / "docs" / "sql" / "museum_book_seed_loadtest.sql"
CSV_OUT = ROOT / "docs" / "jmeter" / "mobiles.csv"
META_OUT = ROOT / "docs" / "jmeter" / "loadtest-meta.properties"

WEIGHTS = [7, 9, 10, 5, 8, 4, 2, 1, 6, 3, 7, 9, 10, 5, 8, 4, 2]
CHECK = "10X98765432"


def id_card(index: int) -> str:
    body = f"11010119900101{index:03d}"
    assert len(body) == 17
    total = sum(int(body[i]) * WEIGHTS[i] for i in range(17))
    return body + CHECK[total % 11]


def main() -> None:
    museum_id = "museum_load"
    now_ms = int(time.time() * 1000)
    today = date.today()
    days = [(today + timedelta(days=i)).isoformat() for i in range(7)]
    meet_day = days[0]
    time_mark = f"{museum_id}_{meet_day}_09:00"
    limit_cnt = 50
    user_count = 80

    lines: list[str] = [
        "-- Auto-generated by generate_loadtest_seed.py",
        "SET NAMES utf8mb4;",
        "USE museum_book;",
        "",
        "DELETE FROM `join` WHERE TIME_MARK LIKE 'museum_load_%' OR USER_ID LIKE 'user_load_%';",
        "DELETE FROM `time` WHERE MUSEUM_ID = 'museum_load';",
        "DELETE FROM `day` WHERE MUSEUM_ID = 'museum_load';",
        "DELETE FROM `identity` WHERE IDENTITY_ID LIKE 'identity_load_%';",
        "DELETE FROM `user` WHERE USER_ID LIKE 'user_load_%';",
        "DELETE FROM `museum` WHERE MUSEUM_ID = 'museum_load';",
        "",
        (
            "INSERT INTO `museum` (`_id`, `MUSEUM_ID`, `MUSEUM_TITLE`, `ADMIN_ID`, `MUSEUM_OBJ`, "
            "`MUSEUM_PIC`, `MUSEUM_MAX_JOIN_CNT`, `MUSEUM_BOOK_SET`, `MUSEUM_STATUS`, "
            "`MUSEUM_ADD_TIME`, `MUSEUM_EDIT_TIME`, `_pid`, `latitude`, `longitude`, `ADDRESS`) VALUES ("
        ),
        (
            f"  'museum_load_pk', 'museum_load', '压测博物馆', 'admin_demo_001', "
            f"'{{\"desc\":\"loadtest\",\"address\":\"北京市东城区压测路1号\"}}', '[]', "
            f"1000, 7, 1, {now_ms}, {now_ms}, '1', 39.916527, 116.397128, '北京市东城区压测路1号'"
        ),
        ");",
        "",
    ]

    for d in days:
        day_id = f"day_load_{d}"
        day_pk = f"daypk_{d}"
        limit_morning = limit_cnt if d == meet_day else 50
        tm_am = f"museum_load_{d}_09:00"
        tm_pm = f"museum_load_{d}_14:00"
        lines.extend(
            [
                (
                    "INSERT INTO `day` (`_id`, `DAY_ID`, `DAY`, `MUSEUM_ID`, `STATUS`, "
                    f"`DAY_LIMIT_CNT`, `ADD_TIME`, `EDIT_TIME`, `_pid`) VALUES ("
                ),
                f"  '{day_pk}', '{day_id}', '{d}', 'museum_load', 1, 100, {now_ms}, {now_ms}, '1'",
                ");",
                (
                    "INSERT INTO `time` (`_id`, `TIME_ID`, `DAY_ID`, `MUSEUM_ID`, `TIME_START`, "
                    "`TIME_END`, `TIME_MARK`, `LIMIT_CNT`, `SUCC_CNT`, `STATUS`, `IS_LIMIT`, "
                    "`ADD_TIME`, `EDIT_TIME`, `_pid`) VALUES"
                ),
                (
                    f"('tmpk_{d}_am', 'time_load_{d}_am', '{day_id}', 'museum_load', '09:00', '11:00', "
                    f"'{tm_am}', {limit_morning}, 0, 1, 1, {now_ms}, {now_ms}, '1'),"
                ),
                (
                    f"('tmpk_{d}_pm', 'time_load_{d}_pm', '{day_id}', 'museum_load', '14:00', '16:00', "
                    f"'{tm_pm}', 50, 0, 1, 1, {now_ms}, {now_ms}, '1');"
                ),
                "",
            ]
        )

    csv_rows = ["mobile,userId,identityId"]
    for i in range(1, user_count + 1):
        n = f"{i:03d}"
        user_id = f"user_load_{n}"
        user_pk = f"userpk_{n}"
        identity_id = f"identity_load_{n}"
        identity_pk = f"idpk_{n}"
        mobile = f"1390000{n}"
        card = id_card(i)
        name = f"压测游客{n}"
        user_id_json = f'["{user_id}"]'
        lines.extend(
            [
                (
                    "INSERT INTO `user` (`_id`, `USER_ID`, `USER_NAME`, `USER_MOBILE`, `USER_PIC`, "
                    f"`USER_ADD_TIME`, `USER_EDIT_TIME`, `_pid`) VALUES ("
                ),
                f"  '{user_pk}', '{user_id}', '用户{n}', '{mobile}', 1, {now_ms}, {now_ms}, '1'",
                ");",
                (
                    "INSERT INTO `identity` (`_id`, `IDENTITY_ID`, `USER_ID`, `IDENTITY_NAME`, "
                    "`IDENTITY_CARD`, `IDENTITY_MOBILE`, `IDENTITY_STATUS`, `USER_BAN_NUM`, "
                    "`USER_CHECK_TYPE`, `_pid`) VALUES ("
                ),
                (
                    f"  '{identity_pk}', '{identity_id}', '{user_id_json}', '{name}', "
                    f"'{card}', '{mobile}', 1, 0, 1, '1'"
                ),
                ");",
            ]
        )
        csv_rows.append(f"{mobile},{user_id},{identity_id}")

    SQL_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    CSV_OUT.write_text("\n".join(csv_rows) + "\n", encoding="utf-8")
    META_OUT.write_text(
        "\n".join(
            [
                f"timeMark={time_mark}",
                f"meetDay={meet_day}",
                f"limitCnt={limit_cnt}",
                f"userCount={user_count}",
                f"museumId={museum_id}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Wrote {SQL_OUT}")
    print(f"Wrote {CSV_OUT}")
    print(f"timeMark={time_mark} limitCnt={limit_cnt} users={user_count}")


if __name__ == "__main__":
    main()
