-- museum_book final schema (aligned with current Entity / database.txt after ALTERs)
-- Safe to re-run on empty database; DROP TABLE IF EXISTS used.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `sys_message`;
DROP TABLE IF EXISTS `sys_message_template`;
DROP TABLE IF EXISTS `relic`;
DROP TABLE IF EXISTS `head`;
DROP TABLE IF EXISTS `log`;
DROP TABLE IF EXISTS `news`;
DROP TABLE IF EXISTS `join`;
DROP TABLE IF EXISTS `time`;
DROP TABLE IF EXISTS `day`;
DROP TABLE IF EXISTS `identity`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `activity`;
DROP TABLE IF EXISTS `museum`;
DROP TABLE IF EXISTS `admin`;

CREATE TABLE `admin` (
  `_id` VARCHAR(64) NOT NULL COMMENT '记录系统唯一标识符',
  `ADMIN_NAME` VARCHAR(50) DEFAULT NULL COMMENT '管理员用户名',
  `ADMIN_PASSWORD` VARCHAR(255) DEFAULT NULL COMMENT '密码 MD5 或明文(登录后升级)',
  `ADMIN_ID` VARCHAR(64) DEFAULT NULL COMMENT '业务主键 ID',
  `ADMIN_TOKEN` VARCHAR(255) DEFAULT NULL COMMENT '登录令牌',
  `ADMIN_TOKEN_TIME` BIGINT DEFAULT NULL COMMENT '令牌生成时间戳',
  `ADMIN_ADD_TIME` BIGINT DEFAULT NULL COMMENT '创建时间戳',
  `_pid` VARCHAR(64) DEFAULT NULL COMMENT '项目标识',
  `ADMIN_NICKNAME` VARCHAR(50) DEFAULT NULL COMMENT '显示用用户名',
  `ADMIN_INTRO` TEXT COMMENT '用户简介',
  `ADMIN_AVATAR` VARCHAR(255) DEFAULT NULL COMMENT '头像图片URL路径',
  `ADMIN_INFO_UPDATE_TIME` BIGINT DEFAULT NULL COMMENT '个人信息更新时间戳',
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管理员表';

CREATE TABLE `museum` (
  `_id` VARCHAR(64) NOT NULL COMMENT '记录系统唯一标识符',
  `MUSEUM_ID` VARCHAR(64) DEFAULT NULL COMMENT '预约项目业务 ID',
  `MUSEUM_TITLE` VARCHAR(255) DEFAULT NULL COMMENT '博物馆标题',
  `ADMIN_ID` VARCHAR(64) DEFAULT NULL COMMENT '创建管理员 ID',
  `MUSEUM_OBJ` LONGTEXT COMMENT '详情对象 JSON',
  `MUSEUM_PIC` LONGTEXT COMMENT '封面图片列表 JSON',
  `MUSEUM_MAX_JOIN_CNT` INT DEFAULT NULL COMMENT '最大预约人数/次数限制',
  `MUSEUM_BOOK_SET` INT DEFAULT NULL COMMENT '可提前x天预约',
  `MUSEUM_STATUS` TINYINT DEFAULT 1 COMMENT '状态 (1: 启用)',
  `MUSEUM_ADD_TIME` BIGINT DEFAULT NULL COMMENT '创建时间戳',
  `MUSEUM_EDIT_TIME` BIGINT DEFAULT NULL COMMENT '修改时间戳',
  `_pid` VARCHAR(64) DEFAULT NULL COMMENT '项目标识',
  `latitude` DOUBLE DEFAULT NULL COMMENT '纬度',
  `longitude` DOUBLE DEFAULT NULL COMMENT '经度',
  `ADDRESS` VARCHAR(550) DEFAULT NULL COMMENT '地址',
  PRIMARY KEY (`_id`),
  KEY `idx_museum_id` (`MUSEUM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='预约项目表';

CREATE TABLE `activity` (
  `_id` VARCHAR(64) NOT NULL COMMENT '记录系统唯一标识符',
  `ACTIVITY_ID` VARCHAR(64) DEFAULT NULL COMMENT '活动业务 ID',
  `ACTIVITY_TITLE` VARCHAR(255) DEFAULT NULL COMMENT '活动标题',
  `ADMIN_ID` VARCHAR(64) DEFAULT NULL COMMENT '创建管理员 ID',
  `ACTIVITY_OBJ` LONGTEXT COMMENT '详情对象 JSON',
  `ACTIVITY_PIC` LONGTEXT COMMENT '封面图片列表 JSON',
  `ACTIVITY_STATUS` TINYINT DEFAULT 1 COMMENT '状态 (1: 启用)',
  `ACTIVITY_ADD_TIME` BIGINT DEFAULT NULL COMMENT '创建时间戳',
  `ACTIVITY_EDIT_TIME` BIGINT DEFAULT NULL COMMENT '修改时间戳',
  `_pid` VARCHAR(64) DEFAULT NULL COMMENT '项目标识',
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动表';

CREATE TABLE `user` (
  `_id` VARCHAR(64) NOT NULL COMMENT '记录系统唯一标识符',
  `USER_ID` VARCHAR(64) DEFAULT NULL COMMENT '用户业务 ID',
  `USER_MINI_OPENID` VARCHAR(128) DEFAULT NULL COMMENT '小程序 OpenID',
  `USER_NAME` VARCHAR(100) DEFAULT NULL COMMENT '用户昵称/姓名',
  `USER_MOBILE` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  `USER_PIC` INT DEFAULT NULL COMMENT '头像',
  `USER_ADD_TIME` BIGINT DEFAULT NULL COMMENT '注册时间戳',
  `USER_EDIT_TIME` BIGINT DEFAULT NULL COMMENT '修改时间戳',
  `_pid` VARCHAR(64) DEFAULT NULL COMMENT '项目标识',
  PRIMARY KEY (`_id`),
  KEY `idx_user_id` (`USER_ID`),
  KEY `idx_user_mobile` (`USER_MOBILE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账号用户表';

CREATE TABLE `identity` (
  `_id` VARCHAR(64) NOT NULL COMMENT '记录系统唯一标识符',
  `IDENTITY_ID` VARCHAR(64) DEFAULT NULL COMMENT '身份用户 ID',
  `USER_ID` TEXT COMMENT '账户ID数组 JSON Array',
  `IDENTITY_NAME` VARCHAR(50) DEFAULT NULL COMMENT '姓名',
  `IDENTITY_CARD` VARCHAR(30) DEFAULT NULL COMMENT '身份证',
  `IDENTITY_MOBILE` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  `IDENTITY_OBJ` TEXT COMMENT '扩展信息 JSON',
  `IDENTITY_STATUS` TINYINT DEFAULT 1 COMMENT '1正常 0黑名单',
  `BLACK_START_TIME` BIGINT DEFAULT NULL COMMENT '拉黑开始时间戳',
  `BLACK_END_TIME` BIGINT DEFAULT NULL COMMENT '拉黑结束时间戳',
  `USER_BAN_NUM` INT DEFAULT 0 COMMENT '违约次数',
  `USER_CHECK_TYPE` TINYINT DEFAULT 1 COMMENT '1自动 0手动拉黑',
  `_pid` VARCHAR(64) DEFAULT NULL COMMENT '项目标识',
  PRIMARY KEY (`_id`),
  UNIQUE KEY `idx_identity_card` (`IDENTITY_CARD`),
  KEY `idx_identity_id` (`IDENTITY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='身份用户表';

CREATE TABLE `day` (
  `_id` VARCHAR(64) NOT NULL COMMENT '记录系统唯一标识符',
  `DAY_ID` VARCHAR(64) DEFAULT NULL COMMENT '主键',
  `DAY` VARCHAR(20) DEFAULT NULL COMMENT '日期 YYYY-MM-DD',
  `MUSEUM_ID` VARCHAR(64) DEFAULT NULL COMMENT '场馆 ID',
  `ACTIVITY_ID` VARCHAR(64) DEFAULT NULL COMMENT '活动 ID',
  `STATUS` TINYINT DEFAULT 1 COMMENT '1可预约 0闭馆',
  `DAY_LIMIT_CNT` INT DEFAULT NULL COMMENT '当天总预约上限',
  `ADD_TIME` BIGINT DEFAULT NULL COMMENT '创建时间戳',
  `EDIT_TIME` BIGINT DEFAULT NULL COMMENT '修改时间戳',
  `_pid` VARCHAR(64) DEFAULT NULL COMMENT '项目标识',
  PRIMARY KEY (`_id`),
  INDEX `idx_day_museum_date` (`MUSEUM_ID`, `DAY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='每日排期表';

CREATE TABLE `time` (
  `_id` VARCHAR(64) NOT NULL COMMENT '记录系统唯一标识符',
  `TIME_ID` VARCHAR(64) DEFAULT NULL COMMENT '主键',
  `DAY_ID` VARCHAR(64) DEFAULT NULL COMMENT '关联 day',
  `MUSEUM_ID` VARCHAR(64) DEFAULT NULL COMMENT '场馆 ID',
  `ACTIVITY_ID` VARCHAR(64) DEFAULT NULL COMMENT '活动 ID',
  `TIME_START` VARCHAR(10) DEFAULT NULL COMMENT '时段开始',
  `TIME_END` VARCHAR(10) DEFAULT NULL COMMENT '时段结束',
  `TIME_MARK` VARCHAR(64) DEFAULT NULL COMMENT '时段唯一标识',
  `LIMIT_CNT` INT DEFAULT NULL COMMENT '时段最大名额',
  `SUCC_CNT` INT DEFAULT 0 COMMENT '已预约人数',
  `STATUS` TINYINT DEFAULT 1 COMMENT '1启用 0禁用',
  `IS_LIMIT` TINYINT DEFAULT 1 COMMENT '是否开启限流',
  `ADD_TIME` BIGINT DEFAULT NULL COMMENT '创建时间',
  `EDIT_TIME` BIGINT DEFAULT NULL COMMENT '修改时间',
  `_pid` VARCHAR(64) DEFAULT NULL COMMENT '项目标识',
  PRIMARY KEY (`_id`),
  UNIQUE KEY `uk_time_mark` (`TIME_MARK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='排期时间段表';

CREATE TABLE `join` (
  `_id` VARCHAR(64) NOT NULL COMMENT '记录系统唯一标识符',
  `JOIN_ID` VARCHAR(64) DEFAULT NULL COMMENT '预约记录业务 ID',
  `IDENTITY_ID` VARCHAR(64) DEFAULT NULL COMMENT '关联人员 ID',
  `USER_ID` VARCHAR(64) DEFAULT NULL COMMENT 'User 业务主键',
  `JOIN_MEET_DAY` VARCHAR(20) DEFAULT NULL COMMENT '预约参观日期',
  `TIME_MARK` VARCHAR(64) DEFAULT NULL COMMENT '时段唯一标识',
  `JOIN_START_TIME` BIGINT DEFAULT NULL COMMENT '预约生效时间戳',
  `JOIN_COMPLETE_END_TIME` VARCHAR(50) DEFAULT NULL COMMENT '完整结束时间字符串',
  `JOIN_STATUS` TINYINT DEFAULT 1 COMMENT '1成功 2取消',
  `JOIN_FORMS` TEXT COMMENT '表单快照 JSON',
  `JOIN_IS_CHECKIN` TINYINT DEFAULT 0 COMMENT '0未核销 1已核销 3逾期',
  `JOIN_QR` TEXT COMMENT '二维码 Base64',
  `JOIN_ADD_TIME` BIGINT DEFAULT NULL COMMENT '下单时间戳',
  `JOIN_EDIT_TIME` BIGINT DEFAULT NULL COMMENT '修改时间戳',
  `_pid` VARCHAR(64) DEFAULT NULL COMMENT '项目标识',
  PRIMARY KEY (`_id`),
  INDEX `idx_join_identity` (`IDENTITY_ID`),
  INDEX `idx_join_user` (`USER_ID`),
  INDEX `idx_join_time_mark` (`TIME_MARK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='预约记录表';

CREATE TABLE `news` (
  `_id` VARCHAR(64) NOT NULL COMMENT '记录系统唯一标识符',
  `NEWS_ID` VARCHAR(64) DEFAULT NULL COMMENT '资讯业务 ID',
  `NEWS_TITLE` VARCHAR(255) DEFAULT NULL COMMENT '标题',
  `NEWS_DESC` TEXT COMMENT '简介',
  `NEWS_STATUS` TINYINT DEFAULT 1 COMMENT '1展示 0下线',
  `NEWS_VIEW_CNT` INT DEFAULT 0 COMMENT '浏览量',
  `NEWS_ADD_TIME` BIGINT DEFAULT NULL COMMENT '创建时间戳',
  `NEWS_EDIT_TIME` BIGINT DEFAULT NULL COMMENT '修改时间戳',
  `_pid` VARCHAR(64) DEFAULT NULL COMMENT '项目标识',
  `NEWS_ADD_IP` VARCHAR(64) DEFAULT NULL COMMENT 'IP',
  `NEWS_EDIT_IP` VARCHAR(64) DEFAULT NULL COMMENT 'IP',
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公告表';

CREATE TABLE `log` (
  `_id` VARCHAR(64) NOT NULL COMMENT '记录系统唯一标识符',
  `LOG_ID` VARCHAR(64) DEFAULT NULL COMMENT '日志业务 ID',
  `LOG_CONTENT` TEXT COMMENT '日志内容',
  `LOG_TYPE` INT DEFAULT 99 COMMENT '0登录 99操作',
  `LOG_ADMIN_ID` VARCHAR(64) DEFAULT NULL COMMENT '操作管理员 ID',
  `LOG_ADMIN_NAME` VARCHAR(50) DEFAULT NULL COMMENT '操作管理员名称',
  `LOG_ADD_TIME` BIGINT DEFAULT NULL COMMENT '记录时间戳',
  `LOG_EDIT_TIME` BIGINT DEFAULT NULL COMMENT '修改时间戳',
  `_pid` VARCHAR(64) DEFAULT NULL COMMENT '项目标识',
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='日志表';

CREATE TABLE `head` (
  `_id` VARCHAR(64) NOT NULL COMMENT '记录系统唯一标识符',
  `HEAD_PIC_ID` VARCHAR(64) DEFAULT NULL COMMENT '头像业务 ID',
  `HEAD_PIC_URL` VARCHAR(255) DEFAULT NULL COMMENT '头像地址',
  `_pid` VARCHAR(64) DEFAULT NULL COMMENT '项目标识',
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='头像数据表';

CREATE TABLE `relic` (
  `_id` VARCHAR(64) NOT NULL COMMENT '主键ID',
  `RELIC_NAME` VARCHAR(255) DEFAULT NULL COMMENT '文物名称',
  `RELIC_DESC` LONGTEXT COMMENT '文物详细介绍',
  `RELIC_IMAGE` VARCHAR(500) DEFAULT NULL COMMENT '文物标准照URL',
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文物信息表';

CREATE TABLE `sys_message` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` VARCHAR(64) NOT NULL COMMENT '接收用户ID',
  `title` VARCHAR(100) DEFAULT NULL COMMENT '消息标题',
  `content` TEXT COMMENT '消息内容',
  `type` TINYINT(2) DEFAULT 0 COMMENT '0系统 1预约 2活动',
  `is_read` TINYINT(1) DEFAULT 0 COMMENT '0未读 1已读',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统消息表';

CREATE TABLE `sys_message_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NOT NULL COMMENT '模版编码',
  `title_template` VARCHAR(100) NOT NULL COMMENT '标题模版',
  `content_template` TEXT NOT NULL COMMENT '内容模版',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消息模版表';

SET FOREIGN_KEY_CHECKS = 1;
